### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Taki21** [OperatingSytemDevs/UnnamedOS#2]
- [ ] Finish Booting Sequence
- [ ] Add a interactive "starting screen"
- [ ] Finish Setup Part
- [ ] Add Login Screen
- [ ] Add 'Forgot Password Option"
- [ ] Finish main OS GUI
- [ ] Finish main OS features
- [ ] Finish built-in OS browser
- [ ] Finish all built-in apps
- [ ] Finish File Systems via formats and file types including a way to open them
- [ ] Finish right click feature
- [ ] Test the OS on like a Virtual Machine Software Like VIrtualBox by Oracle
- [ ] Release to Public as BETA

**Comment by Ad5001** [comment]
Do you have any blank computer to test the software ?

**Comment by TheDragonRing** [comment]
Ok woah :/.... So what language should I try learn for this first?

**Comment by Taki21** [comment]
@Ad5001 said C is good but we also need C++ for security (ill do that C++ and C) For know all of us need to know C.

**Comment by Taki21** [comment]
Or maybe in some cases we might need C# but lets stick to C for now.

**Comment by AmiroEmad** [comment]
sorry taki i will exit i have no knowledge of any of c c# or c++ but unless can help in graphics

**Comment by Taki21** [comment]
yes ok

**Comment by Ad5001** [comment]
When I meaned C, I meaned C# xD

**Comment by Taki21** [comment]
oh lel xD

**Comment by Taki21** [comment]
So i guess its just me and @Ad5001 on this project?

**Comment by Dog2puppy** [comment]
What is the os for? Could make a OS for ComputerCraft (http://computercraft.info/).

**Comment by Taki21** [comment]
...This os is for Computers in real life

**Comment by Dog2puppy** [comment]
Oh. Will it erase the entire computer it's installed on, or will it just be rebooted to use it? And please make it Mac compatible. :)

**Comment by Taki21** [comment]
**rebooted to use it** - U mean live cds? probably ill make a version for that and yes it has to wipe the hard drive but ill make a feature like in windows where it moves to a folder like windows.old folder :) Im not so good with macs gotta do extra research lel

**Comment by iPocket** [comment]
seriously? an Operating System?! LOL

**Comment by Dog2puppy** [comment]
@Taki21 So... Will this be a more for developing (Like Linux) or more of a Every-Day life OS (Windows)?

**Comment by HimbeersaftLP** [comment]
> I thought the same xD

**Comment by Dog2puppy** [comment]
If we do get to the end of this, I don't think it'll become the next Microsoft. XD

**Comment by Dog2puppy** [comment]
Hmm... Let's make the next version of Chrome OS, and sell it to google for millions of dollars and it would be the first version of ChromeOS open-sourced.

**Comment by Taki21** [comment]
I was thinking more like Android and Windows  together as 1 OS with very light designs
